# Generated by Django 5.1.6 on 2025-03-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_loyalty', '0003_alter_clientloyalty_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientloyalty',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=8),
        ),
    ]
