# Generated by Django 5.1.6 on 2025-03-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_loyalty', '0004_clientloyalty_status'),
        ('clients', '0002_remove_client_image_url'),
        ('companies', '0004_company_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientloyalty',
            unique_together={('client', 'company')},
        ),
    ]
