# Generated by Django 5.1.6 on 2025-03-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bonus_points_ratio',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=3),
        ),
        migrations.AddField(
            model_name='company',
            name='max_sale',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
        ),
    ]
