# Generated by Django 5.1.6 on 2025-03-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='image_url',
        ),
    ]
