# Generated by Django 5.1.6 on 2025-03-03 00:52

import django_minio_backend.models
import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='hnz-company-items'), upload_to=items.models.item_image_upload_to),
        ),
    ]
