# Generated by Django 5.1.6 on 2025-03-03 16:54

import items.models
import loyalT.minio
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=loyalT.minio.LoyalTMinioBackend(bucket_name='hnz-company-items'), upload_to=items.models.item_image_upload_to),
        ),
    ]
